#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${1:-my-project}"

DIRECTORIES=(
  "$PROJECT_ROOT/backend/app/api/routes"
  "$PROJECT_ROOT/backend/app/core"
  "$PROJECT_ROOT/backend/app/models"
  "$PROJECT_ROOT/backend/app/repositories"
  "$PROJECT_ROOT/backend/app/schemas"
  "$PROJECT_ROOT/backend/app/services"
  "$PROJECT_ROOT/backend/app/cli"
  "$PROJECT_ROOT/backend/tests"
  "$PROJECT_ROOT/backend/data"
  "$PROJECT_ROOT/frontend/public/models"
  "$PROJECT_ROOT/frontend/src/assets"
  "$PROJECT_ROOT/frontend/src/components"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/components"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/hooks"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/services"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/store"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/model"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/workers"
  "$PROJECT_ROOT/.github/workflows"
  "$PROJECT_ROOT/.github/ISSUE_TEMPLATE"
  "$PROJECT_ROOT/docs"
  "$PROJECT_ROOT/scripts"
)

FILES=(
  "$PROJECT_ROOT/backend/__init__.py"
  "$PROJECT_ROOT/backend/app/__init__.py"
  "$PROJECT_ROOT/backend/app/api/__init__.py"
  "$PROJECT_ROOT/backend/app/api/dependencies.py"
  "$PROJECT_ROOT/backend/app/main.py"
  "$PROJECT_ROOT/backend/app/api/router.py"
  "$PROJECT_ROOT/backend/app/api/routes/__init__.py"
  "$PROJECT_ROOT/backend/app/api/routes/catalogs.py"
  "$PROJECT_ROOT/backend/app/api/routes/health.py"
  "$PROJECT_ROOT/backend/app/core/__init__.py"
  "$PROJECT_ROOT/backend/app/core/config.py"
  "$PROJECT_ROOT/backend/app/models/__init__.py"
  "$PROJECT_ROOT/backend/app/models/catalog.py"
  "$PROJECT_ROOT/backend/app/repositories/__init__.py"
  "$PROJECT_ROOT/backend/app/repositories/catalogs.py"
  "$PROJECT_ROOT/backend/app/schemas/__init__.py"
  "$PROJECT_ROOT/backend/app/schemas/catalog.py"
  "$PROJECT_ROOT/backend/app/services/__init__.py"
  "$PROJECT_ROOT/backend/app/services/arrow_stream.py"
  "$PROJECT_ROOT/backend/app/cli/__init__.py"
  "$PROJECT_ROOT/backend/app/cli/ingest.py"
  "$PROJECT_ROOT/backend/tests/__init__.py"
  "$PROJECT_ROOT/backend/main.py"
  "$PROJECT_ROOT/backend/requirements.txt"
  "$PROJECT_ROOT/backend/requirements-dev.txt"
  "$PROJECT_ROOT/frontend/index.html"
  "$PROJECT_ROOT/frontend/src/App.tsx"
  "$PROJECT_ROOT/frontend/src/main.tsx"
  "$PROJECT_ROOT/frontend/src/assets/styles.css"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/components/Canvas.tsx"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/components/SceneViewport.tsx"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/services/seismicApi.ts"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/store/viewerStore.ts"
  "$PROJECT_ROOT/frontend/src/features/seismic-viewer/model/types.ts"
  "$PROJECT_ROOT/frontend/public/models/.gitkeep"
  "$PROJECT_ROOT/frontend/vite.config.ts"
  "$PROJECT_ROOT/frontend/tsconfig.json"
  "$PROJECT_ROOT/frontend/package.json"
  "$PROJECT_ROOT/.github/workflows/ci.yml"
  "$PROJECT_ROOT/.github/dependabot.yml"
  "$PROJECT_ROOT/.github/pull_request_template.md"
  "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/bug_report.yml"
  "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/feature_request.yml"
  "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/config.yml"
  "$PROJECT_ROOT/scripts/setup.sh"
  "$PROJECT_ROOT/scripts/dev.sh"
  "$PROJECT_ROOT/scripts/check.sh"
  "$PROJECT_ROOT/package.json"
  "$PROJECT_ROOT/Makefile"
  "$PROJECT_ROOT/CONTRIBUTING.md"
  "$PROJECT_ROOT/SECURITY.md"
  "$PROJECT_ROOT/CODE_OF_CONDUCT.md"
  "$PROJECT_ROOT/CHANGELOG.md"
  "$PROJECT_ROOT/DEVELOPMENT_HISTORY.md"
  "$PROJECT_ROOT/docs/architecture.md"
  "$PROJECT_ROOT/docs/publishing-checklist.md"
  "$PROJECT_ROOT/README.md"
)

mkdir -p "${DIRECTORIES[@]}"
touch "${FILES[@]}"

echo "Created project skeleton at: $PROJECT_ROOT"
